global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-login-job"
    metrics_path: "/monitoring/prometheus"
    static_configs:
      - targets: ["docker.for.mac.host.internal:8080"]
        labels:
          application: "api-login"